'use client';
import { useEffect, useState } from 'react';
import { createClient } from '@/lib/supabase/client';
import { updateOrderStatus } from './actions';

type Order = { id: string; order_number: string; status: string; subtotal: number; shipping_fee: number; total_amount: number; currency: string; created_at: string; customer_id: string };
const statuses = ['pending','confirmed','processing','shipped','out_for_delivery','delivered','cancelled','refunded'] as const;
export default function AdminOrdersPage() {
 const [rows,setRows]=useState<Order[]>([]); const [message,setMessage]=useState(''); const [loading,setLoading]=useState(true);
 async function load(){const s=createClient();const{data:{user}}=await s.auth.getUser();if(!user){location.href='/login';return}const{data:p}=await s.from('profiles').select('role').eq('id',user.id).single();if(p?.role!=='admin'){location.href='/';return}const{data}=await s.from('orders').select('id,order_number,status,subtotal,shipping_fee,total_amount,currency,created_at,customer_id').order('created_at',{ascending:false});setRows((data||[]) as Order[]);setLoading(false)}
 useEffect(()=>{load()},[]);
 async function change(id:string,status:typeof statuses[number]){const r=await updateOrderStatus({orderId:id,status});setMessage(r.success?`Order updated to ${status.replaceAll('_',' ')}.`:r.error||'Unable to update order.');await load()}
 if(loading)return <main className="min-h-screen bg-gray-50 p-8">Loading orders…</main>;
 return <main className="min-h-screen bg-gray-50 p-4 sm:p-8"><div className="mx-auto max-w-7xl space-y-6"><header><p className="text-sm font-semibold text-[#0f2b5b]">Operations</p><h1 className="text-3xl font-bold">Orders</h1><p className="mt-1 text-sm text-gray-500">Monitor and control the complete marketplace order lifecycle.</p></header>{message&&<div className="rounded-xl border bg-white p-4 text-sm">{message}</div>}<section className="overflow-hidden rounded-2xl border bg-white"><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="border-b bg-gray-50"><tr><th className="px-5 py-4 text-left">Order</th><th className="px-5 py-4 text-left">Date</th><th className="px-5 py-4 text-left">Total</th><th className="px-5 py-4 text-left">Status</th><th className="px-5 py-4 text-right">Update</th></tr></thead><tbody>{rows.map(o=><tr key={o.id} className="border-b last:border-0"><td className="px-5 py-4"><p className="font-semibold">{o.order_number}</p><p className="text-xs text-gray-400">{o.customer_id.slice(0,8)}</p></td><td className="px-5 py-4 text-gray-600">{new Date(o.created_at).toLocaleString()}</td><td className="px-5 py-4 font-semibold">{o.currency} {Number(o.total_amount).toFixed(2)}</td><td className="px-5 py-4"><span className="rounded-full bg-gray-100 px-3 py-1 text-xs font-semibold capitalize">{o.status.replaceAll('_',' ')}</span></td><td className="px-5 py-4 text-right"><select value={o.status} onChange={e=>change(o.id,e.target.value as typeof statuses[number])} className="rounded-lg border px-2 py-2 text-xs">{statuses.map(status=><option key={status} value={status}>{status.replaceAll('_',' ')}</option>)}</select></td></tr>)}</tbody></table></div>{rows.length===0&&<p className="p-10 text-center text-sm text-gray-500">No orders yet.</p>}</section></div></main>;
}
