'use server';
import { createClient } from '@/lib/supabase/server';
import { revalidatePath } from 'next/cache';

async function admin(){const supabase=await createClient();const {data:claims}=await supabase.auth.getClaims();const uid=typeof claims?.claims?.sub==='string'?claims.claims.sub:null;if(!uid)return null;const {data:p}=await supabase.from('profiles').select('role').eq('id',uid).single();return p?.role==='admin'?supabase:null;}
export async function setSellerStatus(id:string,status:'pending'|'active'|'suspended'|'rejected'){const supabase=await admin();if(!supabase)return{success:false,error:'Admin access required'};const {error}=await (supabase as any).rpc('admin_set_seller_status',{p_seller_id:id,p_status:status});if(error)return{success:false,error:error.message};revalidatePath('/admin/dashboard');revalidatePath('/seller/apply');return{success:true};}
export async function setOrderStatus(id:string,status:string){const supabase=await admin();if(!supabase)return{success:false,error:'Admin access required'};const {error}=await (supabase as any).rpc('admin_set_order_status',{p_order_id:id,p_status:status});if(error)return{success:false,error:error.message};revalidatePath('/admin/dashboard');revalidatePath('/account/orders');return{success:true};}
export async function setProductStatus(id:string,status:'draft'|'pending_review'|'active'|'inactive'|'rejected'){const supabase=await admin();if(!supabase)return{success:false,error:'Admin access required'};const {error}=await supabase.from('products').update({status}).eq('id',id);if(error)return{success:false,error:error.message};revalidatePath('/admin/dashboard');revalidatePath('/products');return{success:true};}
export async function setReviewPublished(id:string,published:boolean){const supabase=await admin();if(!supabase)return{success:false,error:'Admin access required'};const {error}=await supabase.from('reviews').update({is_published:published}).eq('id',id);if(error)return{success:false,error:error.message};revalidatePath('/admin/dashboard');return{success:true};}
