'use client';
import { useEffect, useState } from 'react';
import { createClient } from '@/lib/supabase/client';
import { updatePayout } from './actions';
type Payout = { id: string; seller_id: string; order_item_id: string | null; gross_amount: number; commission_amount: number; net_amount: number; currency: string; status: string; paid_at: string | null; created_at: string; sellers?: { store_name: string } | null };
export default function AdminPayoutsPage() {
  const [rows, setRows] = useState<Payout[]>([]); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(true);
  async function load() { const supabase = createClient() as any; const { data: { user } } = await supabase.auth.getUser(); if (!user) { location.href = '/login'; return; } const { data: profile } = await supabase.from('profiles').select('role').eq('id', user.id).single(); if (profile?.role !== 'admin') { location.href = '/'; return; } const { data } = await supabase.from('seller_payouts').select('id,seller_id,order_item_id,gross_amount,commission_amount,net_amount,currency,status,paid_at,created_at,sellers(store_name)').order('created_at', { ascending: false }); setRows((data || []) as Payout[]); setLoading(false); }
  useEffect(() => { load(); }, []);
  async function changeStatus(id: string, status: 'pending' | 'processing' | 'paid' | 'failed') { const result = await updatePayout({ payoutId: id, status }); setMessage(result.success ? `Payout marked ${status}.` : result.error || 'Unable to update payout.'); await load(); }
  if (loading) return <main className="min-h-screen bg-gray-50 p-8">Loading payouts…</main>;
  const pending = rows.filter((row) => row.status === 'pending').reduce((sum, row) => sum + Number(row.net_amount), 0);
  return <main className="min-h-screen bg-gray-50 p-4 sm:p-8"><div className="mx-auto max-w-7xl space-y-6"><header><p className="text-sm font-semibold text-[#0f2b5b]">Finance</p><h1 className="text-3xl font-bold text-gray-900">Seller payouts</h1><p className="mt-1 text-sm text-gray-500">Review and settle seller balances. External bank/provider transfer is intentionally manual until a payout provider is configured.</p></header>{message && <div className="rounded-xl border bg-white p-4 text-sm">{message}</div>}<div className="grid gap-4 sm:grid-cols-3"><div className="rounded-2xl border bg-white p-5"><p className="text-sm text-gray-500">Payout records</p><p className="mt-2 text-2xl font-bold">{rows.length}</p></div><div className="rounded-2xl border bg-white p-5"><p className="text-sm text-gray-500">Pending value</p><p className="mt-2 text-2xl font-bold">GHS {pending.toFixed(2)}</p></div><div className="rounded-2xl border bg-white p-5"><p className="text-sm text-gray-500">Paid records</p><p className="mt-2 text-2xl font-bold">{rows.filter((r) => r.status === 'paid').length}</p></div></div><section className="overflow-hidden rounded-2xl border bg-white"><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="border-b bg-gray-50"><tr><th className="px-5 py-4 text-left">Seller</th><th className="px-5 py-4 text-left">Gross</th><th className="px-5 py-4 text-left">Commission</th><th className="px-5 py-4 text-left">Net</th><th className="px-5 py-4 text-left">Status</th><th className="px-5 py-4 text-right">Action</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id} className="border-b last:border-0"><td className="px-5 py-4 font-medium">{row.sellers?.store_name || row.seller_id.slice(0, 8)}</td><td className="px-5 py-4">GHS {Number(row.gross_amount).toFixed(2)}</td><td className="px-5 py-4">GHS {Number(row.commission_amount).toFixed(2)}</td><td className="px-5 py-4 font-semibold">GHS {Number(row.net_amount).toFixed(2)}</td><td className="px-5 py-4"><span className="rounded-full bg-gray-100 px-3 py-1 text-xs font-semibold capitalize">{row.status}</span></td><td className="px-5 py-4 text-right"><select value={row.status} onChange={(e) => changeStatus(row.id, e.target.value as 'pending' | 'processing' | 'paid' | 'failed')} className="rounded-lg border px-2 py-2 text-xs"><option value="pending">Pending</option><option value="processing">Processing</option><option value="paid">Paid</option><option value="failed">Failed</option></select></td></tr>)}</tbody></table></div>{rows.length === 0 && <p className="p-10 text-center text-sm text-gray-500">No payout records yet. They are generated automatically when an order is delivered.</p>}</section></div></main>;
}
