'use client';
import{useEffect,useState}from'react';
import{createClient}from'@/lib/supabase/client';
import{updateSellerStatus}from'./actions';
type Seller={id:string;store_name:string;status:string;commission_rate:number;created_at:string;owner_id:string};
type SellerStatus='pending'|'active'|'suspended'|'rejected';
const statuses:SellerStatus[]=['pending','active','suspended','rejected'];
export default function AdminSellersPage(){
 const[rows,setRows]=useState<Seller[]>([]);const[message,setMessage]=useState('');const[loading,setLoading]=useState(true);const[busy,setBusy]=useState<string|null>(null);
 async function load(){const s=createClient() as any;const{data:{user}}=await s.auth.getUser();if(!user){location.href='/login';return}const{data:p}=await s.from('profiles').select('role').eq('id',user.id).single();if(p?.role!=='admin'){location.href='/';return}const{data,error}=await s.from('sellers').select('id,store_name,status,commission_rate,created_at,owner_id').order('created_at',{ascending:false});if(error){setMessage(error.message)}else{setRows((data||[]) as Seller[])}setLoading(false)}
 useEffect(()=>{load()},[]);
 async function change(id:string,status:SellerStatus){setBusy(id);setMessage('');const r=await updateSellerStatus({sellerId:id,status});if(r.success){setMessage(`Seller marked ${status}.`);await load()}else setMessage(r.error||'Unable to update seller.');setBusy(null)}
 if(loading)return <main className="min-h-screen bg-gray-50 p-8">Loading sellers…</main>;
 return <main className="min-h-screen bg-gray-50 p-4 sm:p-8"><div className="mx-auto max-w-7xl space-y-6"><header><p className="text-sm font-semibold text-[#0f2b5b]">Marketplace partners</p><h1 className="text-3xl font-bold">Sellers</h1><p className="mt-1 text-sm text-gray-500">Approve applications, reject unsuitable applications, or suspend active sellers.</p></header>{message&&<div className="rounded-xl border bg-white p-4 text-sm">{message}</div>}<section className="overflow-hidden rounded-2xl border bg-white"><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="border-b bg-gray-50"><tr><th className="px-5 py-4 text-left">Store</th><th className="px-5 py-4 text-left">Status</th><th className="px-5 py-4 text-left">Commission</th><th className="px-5 py-4 text-left">Joined</th><th className="px-5 py-4 text-right">Action</th></tr></thead><tbody>{rows.map(s=><tr key={s.id} className="border-b last:border-0"><td className="px-5 py-4"><p className="font-semibold">{s.store_name}</p><p className="text-xs text-gray-400">Owner {s.owner_id.slice(0,8)}</p></td><td className="px-5 py-4"><span className="rounded-full bg-gray-100 px-3 py-1 text-xs font-semibold capitalize">{s.status}</span></td><td className="px-5 py-4">{Number(s.commission_rate).toFixed(2)}%</td><td className="px-5 py-4 text-gray-600">{new Date(s.created_at).toLocaleDateString()}</td><td className="px-5 py-4 text-right"><select disabled={busy===s.id} value={s.status} onChange={e=>change(s.id,e.target.value as SellerStatus)} className="rounded-lg border px-2 py-2 text-xs"><option value="pending">Pending</option><option value="active">Approve</option><option value="suspended">Suspend</option><option value="rejected">Reject</option></select></td></tr>)}</tbody></table></div>{rows.length===0&&<p className="p-10 text-center text-sm text-gray-500">No seller accounts yet.</p>}</section></div></main>}
